### ISSUE TITLE
tutorial test_000 fails

### ISSUE THREAD

**Issue by stanislas-brossette** [bip-team/humoto#1]
After first installation of humoto with make all. test_000 returns:
./test_000
In readNestedConfig() // Failed to parse node <SolverParameters> in the configuration file: In readScalar() // Configuration file does not contain entry 'solve_two_levels_as_qp'.

**Comment by asherikov** [comment]
Added missing entry in configuration file (wpg04/test_000).
PS: Please, always specifiy the module -- there are many test_000.
