### ISSUE TITLE
linker flags

### ISSUE THREAD

**Issue by asherikov** [bip-team/humoto#22]
Guys, I guess the problem that you have is that you are not using GNU linker on MAC OS. Note that "HUMOTO_SHARED_GNU_LINKER_FLAGS" was intended to be used with GNU linker only (as suggested by the name of the variable). If the linker is different, don't use these flags at all. 

Ideally, we should identify the linker and set flags accordingly -- configuration must be specific to a linker, not a platform.

**Comment by TeoKa** [comment]
Thanks Alexander!
Currently, we decided to set it off in case of compiling in Mac.

**Comment by asherikov** [comment]
What I mean is that you are using "HUMOTO_SHARED_GNU_LINKER_FLAGS" with a non GNU linker. This may be confusing and must be fixed. Temporary hacks should not stay in the master branch for long.

**Comment by TeoKa** [comment]
I understand, ok as soon as Jan is back we change that.
